name: Django CI/CD - M03 Selenium

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

   
    - name: Install Firefox and Geckodriver
      run: |
        sudo apt-get update
        # Instal·lem Firefox i Geckodriver
        sudo apt-get install -y firefox geckodriver

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install webdriver-manager

    - name: Run Django Selenium Tests
      run: |
        
        export PATH=$PATH:/usr/bin
        
        export PYTHONPATH=.
        
        python manage.py test polls.tests_selenium --settings=djproject52.settings
