name: Django CI/CD - M03 Selenium

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Google Chrome Stable
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install ChromeDriver matching Chrome version
      uses: nanasess/setup-chromedriver@v2
      with:
        chrome-version: "stable"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run Django Selenium Tests
      env:
        DISPLAY: :99
      run: |
        export PATH=$PATH:/usr/bin
        python manage.py test polls.tests_selenium --settings=djproject52.settings
